set $term "(ELM_DISPLAY=wl terminology --borderless)"
set $term_cwd "(ELM_DISPLAY=wl terminology --borderless)"

# Audio control
set $refresh_py3status py3-cmd refresh volume_status
set $volume_down $volume_down & $refresh_py3status
set $volume_up $volume_up & $refresh_py3status
set $volume_mute $volume_mute & $refresh_py3status
set $mic_mute $mic_mute & $refresh_py3status